- name: corrige permissões da chave ssh
  hosts: localhost
  connection: local 
  tasks:
    - name: corrige permissões da chave ssh
      shell: chmod 400 {{playbook_dir}}/{{env}}/pet-clinic

- name: postgresql 
  remote_user: ec2-user
  hosts: tag_Name_pet_clinic_db_{{env}}
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/{{env}}/pet-clinic"
  roles: 
    - common-server
    - postgres

- name: configurações de banco para aplicação pet-clinic
  remote_user: ec2-user
  hosts: tag_Name_pet_clinic_db_{{env}}
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/{{env}}/pet-clinic"
  roles: 
    - postgres-config-petclinic