---
- name: cria o banco do petclinic
  become: true
  become_user: postgres
  community.postgresql.postgresql_db: 
    name: petclinic
    template: template0
    state: present

- name: reseta senha do postgresql para o banco petclinic
  become: yes
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_user: 
    db: petclinic
    name: petclinic-user
    password: petclinic-passwd