---
- name: instala haproxy
  yum:
    name:
      - haproxy
    state: present
  notify: restart haproxy

- name: debug
  debug:
    var: groups
    
- name: configura haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: systemctl haproxy enabled
  service:
    name: haproxy
    state: started
    enabled: yes

