---
- name: pet-clinic build
  hosts: localhost
  connection: local 
  tasks:
    - name: Clone do projeto
      git:
        repo: https://github.com/mycloudlab/pet-clinic-demo-aap
        dest: src
        single_branch: yes
        version: main

    - name: compile
      shell: mvn clean package -DskipTests
        strip_empty_ends: false
      args:
        chdir: src
#      async: 1000
#     poll: 0
#      register: mvn_build

#    - name: aguarda compilação
#      ansible.builtin.async_status:
#        jid: '{{ mvn_build.ansible_job_id }}'
#      register: job_result
#      until: job_result.finished
#      retries: 100
#      delay: 1