---
- name: pet-clinic build
  hosts: localhost
  connection: local 
  tasks:
    - name: build
      shell: cat /home/runner/.sdkman/candidates/maven/current/conf/settings.xml

    - name: build java
      shell: java -version