---
- name: pet-clinic webhook
  hosts: localhost
  connection: local 
  vars_files:
    - dev/config.yml
    - hom/config.yml
    - prod/config.yml
  tasks:

    - name: Executa sync em desenvolvimento
      ansible.controller.workflow_launch:
        workflow_template: "sync-petclinic-dev"
        extra_vars:
          env: dev
          AWS_REGION: us-east-2
          APP_VERSION: "{{ dev_version }}"
        wait: False
      when: hostvars['localhost']['petclinic_dev_version'] is defined and dev_version != hostvars['localhost']['petclinic_dev_version'] 

    - name: Executa sync em homologação
      ansible.controller.workflow_launch:
        workflow_template: "sync-petclinic-hom"
        extra_vars:
          env: hom
          AWS_REGION: us-east-2
          APP_VERSION: "{{ hom_version }}"
        wait: False
      when: hostvars['localhost']['petclinic_hom_version'] is defined and hom_version != hostvars['localhost']['petclinic_hom_version'] 

    - name: Executa sync em produção
      ansible.controller.workflow_launch:
        workflow_template: "sync-petclinic-prod"
        extra_vars:
          env: prod
          AWS_REGION: us-east-2
          APP_VERSION: "{{ prod_version }}"
        wait: False
      when: hostvars['localhost']['petclinic_prod_version'] is defined and prod_version != hostvars['localhost']['petclinic_prod_version'] 

    - name: Define as versões de aplicação
      set_fact:
        petclinic_dev_version: "{{ dev_version }}"
        petclinic_hom_version: "{{ hom_version }}"
        petclinic_prod_version: "{{ prod_version }}"
        cacheable: yes