---
- name: pet-clinic webhook
  hosts: localhost
  connection: local 
  tasks:
    - name: show before fact 
      debug: 
        msg: disparadso {{ ansible_facts.one_fact| default(omit) }}
    
    - name: show before fact 
      debug: 
        msg: disparado {{ one_fact | default(omit) }}
    
    - name: define fact 
      set_fact:
        one_fact: something
        cacheable: yes

    - name: webhook 
      debug: 
        msg: disparado2 disparado {{ one_fact | default(omit) }}