---
- name: pet-clinic webhook
  hosts: localhost
  connection: local 
  vars_files:
    - dev/config.yml
    - hom/config.yml
    - prod/config.yml
  tasks:

    - name: Executa sync em desenvolvimento
      ansible.controller.workflow_launch:
        workflow_template: "sync-petclinic-dev"
        extra_vars:
          var1: My First Variable
          var2: My Second Variable
        wait: False
      when: dev_version != hostvars['localhost']['petclinic_dev_version'] 

    - name: Define as versões de aplicação
      set_fact:
        petclinic_dev_version: "{{ dev_version }}"
        petclinic_hom_version: "{{ hom_version }}"
        petclinic_prod_version: "{{ prod_version }}"
        cacheable: yes