---
- name: pet-clinic webhook
  hosts: localhost
  connection: local 
  tasks:
    - name: show before fact 
      debug:  
        msg: "{{ hostvars['localhost']['app_version'] | default(omit)  }}"
    
    - name: define fact 
      set_fact:
        app_version: 1.45     
        cacheable: yes

    - name: webhook 
      debug: 
        msg: disparado2 disparado {{ app_version  }}