---
- name: pet-clinic webhook
  hosts: localhost
  connection: local 
  tasks:
    - name: show before fact 
      debug:  
        msg: "{{ hostvars['localhost']['one_fact'] }}"
    
    - name: define fact 
      set_fact:
        one_fact: something
        cacheable: yes

    - name: webhook 
      debug: 
        msg: disparado2 disparado {{ one_fact  }}