---
- name: pet-clinic webhook
  hosts: localhost
  connection: local 
  vars_files:
    - dev/config.yml
    - hom/config.yml
    - prod/config.yml
  tasks:
    - name: Launch a job
      ansible.controller.workflow_launch:
        workflow_template: "sync-petclinic-dev"
        extra_vars:
          var1: My First Variable
          var2: My Second Variable

    - name: show before fact 
      debug:  
        msg: "{{ hostvars['localhost']['app_version'] | default(omit)  }}"
    
    - name: define fact 
      set_fact:
        app_version: 1.46   
        cacheable: yes
 
    - name: webhook 
      debug: 
        msg: disparado2 disparado {{ app_version  }}