- name: Ansible test
  hosts: localhost
  connection: local 
  tasks:

  - name: corrige permissoes da chave ssh
    shell: chmod 400 {{playbook_dir}}/pet-clinic-dev

- name: ansible app
  hosts: tag_Name_pet_clinic_app_dev
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: "{{playbook_dir}}/pet-clinic-dev"
  tasks:
  - name: configura app
    shell: touch /tmp/app