# Basic provisioning example
- name: Ansible test
  hosts: all
  tasks:
  - name: criar vpc para aplicação pet-clinic
    ec2_vpc_net:
      name: vpc_petclinic_dev
      cidr_block: 10.10.0.0/16
      region: us-east-2
      tags:
        app: pet clinic
        env: dev
      tenancy: dedicated
    register: vpcdata

  - name: cria a sub rede da aplicação
    amazon.aws.ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcdata.vpc.id}}"
      region: us-east-2
      cidr: 10.10.0.0/16
      tags:
        app: pet clinic
        env: dev
    register: subnetdata

#  - name: debug
#    debug:
#      var: subnetdata

  - name: ec2 security group
    amazon.aws.ec2_group:
      name: sec_group_petclinic
      description: an example EC2 group
      vpc_id: "{{vpcdata.vpc.id}}"
      region: us-east-2
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 10.0.0.0/8
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0

  - name: launching AWS instance using Ansible
    ec2:
      key_name: aws_instance_Ansible
      instance_type: t2.micro
      image: ami-0abcb3d13703a4978
      region: us-east-2
      wait: yes
      group: sec_group_petclinic
      count: 1
      vpc_subnet_id: "{{ subnetdata.subnet.id }}"
      assign_public_ip: yes
      tenancy: dedicated
