---
- name: pet-clinic build
  hosts: localhost
  connection: local 
  vars_files:
    - vars.yml

  tasks:
     
 #   - name: Clone do projeto
 #     git:
 #       repo: https://github.com/mycloudlab/pet-clinic-demo-aap
 #       dest: src
 #       single_branch: yes
 #       version: main
 
#    - name: obtem a versão da aplicação
#      shell: cd src && git rev-parse --short HEAD
#      register: version

#    - name: muda a versão para o commit hash 
#      shell: mvn versions:set -DgenerateBackupPoms=false -DnewVersion={{version.stdout}}
#      args:
#        chdir: src

#    - name: compile
#      shell: mvn clean package deploy -DskipTests
#      args:
#        chdir: src

#    - name: Creates directory
#      file:
#        path: /home/runner/.ssh
#        state: directory

    - name: Creates directory
      shell: mkdir .ssh

    - name: Ensure GitHub deploy key is present on the server.
      copy:
        content: "{{ git_petclinic_infra_key }}"
        dest: .ssh/id_ed25519

    - name: Ensure GitHub deploy key is present on the server.
      copy:
        content: "{{ git_petclinic_infra_pub }}"
        dest: .ssh/id_ed25519.pub

#    - name: user id
#      shell: ls -la .ssh


    - name: set permission
      shell: cd .ssh && chmod 600 * -R

    

    - name: chave publica
      shell: cat .ssh/id_ed25519.pub


    - name: chave 
      shell: cat .ssh/id_ed25519

    
    
    - name: Clone do projeto de infraestrutura
      shell: HOME=$PWD GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:mycloudlab/demo-ansible.git infra
    
   # podman run --rm -v ${HOME}/.ssh/id_ed25519.pub:/home/runner/.ssh/id_ed25519.pub -v ${HOME}/.ssh/id_ed25519:/home/runner/.ssh/id_ed25519 -it teste bash

    
    - name: seta a versão nova em desenvolvimento
      copy:
        content: "dev_version: {{ version.stdout }}"
        dest: infra/configs/dev/config.yml

    - name: commit new version
      shell: cd infra && git add . && git commit -a -m "update dev version" && git push

