---
- name: pet-clinic build
  hosts: localhost
  connection: local 
  vars_files:
    - vars.yml

  tasks:
     
    - name: Clone do projeto
      git:
        repo: https://github.com/mycloudlab/pet-clinic-demo-aap
        dest: src
        single_branch: yes
        version: main
 
    - name: obtem a versão da aplicação
      shell: cd src && git rev-parse --short HEAD
      register: version

    - name: muda a versão para o commit hash 
      shell: mvn versions:set -DgenerateBackupPoms=false -DnewVersion={{version.stdout}}
      args:
        chdir: src

    - name: compile
      shell: mvn clean package deploy -DskipTests
      args:
        chdir: src

    - name: Ensure GitHub deploy key is present on the server.
      copy:
        content: "{{ git_petclinic_infra_key }}"
        dest: infra_key
        mode: 0600

    - name: Clone do projeto de infraestrutura
      shell: git config --add  core.sshCommand 'ssh -i $(pwd)/infra_key' && git clone git@github.com:mycloudlab/demo-ansible.git infra
    
    - name: seta a versão nova em desenvolvimento
      copy:
        content: "dev_version: {{ version.stdout }}"
        dest: infra/configs/dev/config.yml

    - name: commit new version
      shell: GIT_SSH_COMMAND='ssh -o "StrictHostKeyChecking=no" -i $(pwd)/infra_key' && cd infra && git add . && git commit -a -m "update dev version" && git push