---
- name: pet-clinic build
  hosts: localhost
  connection: local 
  tasks:
    - name: Clone do projeto
      git:
        repo: https://github.com/mycloudlab/pet-clinic-demo-aap
        dest: src
        single_branch: yes
        version: main
 
    - name: muda a versão para o commit hash 
      shell: mvn versions:set -DnewVersion=$(git log -1 --format="%H")
      args:
        chdir: src

    - name: compile
      shell: mvn clean package deploy -DskipTests
      args:
        chdir: src