---
- name: pet-clinic build
  hosts: localhost
  connection: local 
  vars_files:
    - vars.yml

  tasks:
    - name: recuperar conteudo chave
      debug:
        msg: "{{ git_petclinic_infra_key }}"

    - name: para
      shell: "false"
     
    - name: Clone do projeto
      git:
        repo: https://github.com/mycloudlab/pet-clinic-demo-aap
        dest: src
        single_branch: yes
        version: main
 
    - name: muda a versão para o commit hash 
      shell: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$(git rev-parse --short HEAD)
      args:
        chdir: src

    - name: compile
      shell: mvn clean package deploy -DskipTests
      args:
        chdir: src



#    - name: Clone do projeto de infraestrutura
#      git:
#        repo: git@github.com:mycloudlab/demo-ansible.git
#        dest: infra
#        single_branch: yes
#        version: main
#        key_file: 