---
- name: pet-clinic build
  hosts: localhost
  connection: local 
  vars_files:
    - vars.yml

  tasks:
     
    - name: Clone do projeto
      git:
        repo: https://github.com/mycloudlab/pet-clinic-demo-aap
        dest: src
        single_branch: yes
        version: main
 
    - name: obtem a versão da aplicação
      shell: cd src && git rev-parse --short HEAD
      register: version

    - name: muda a versão para o commit hash 
      shell: mvn versions:set -DgenerateBackupPoms=false -DnewVersion={{version.stdout}}
      args:
        chdir: src

    - name: compile
      shell: mvn clean package deploy -DskipTests
      args:
        chdir: src

    - name: Creates directory
      file:
        path: /home/runner/.ssh
        state: directory

    - name: Ensure GitHub deploy key is present on the server.
      copy:
        content: "{{ git_petclinic_infra_key }}"
        dest: /home/runner/.ssh/id_rsa
        mode: 0600

    - name: Ensure GitHub deploy key is present on the server.
      copy:
        content: "{{ git_petclinic_infra_pub }}"
        dest: /home/runner/.ssh/id_rsa.pub
        mode: 0600


    - name: commit new version
      shell: ls /home/runner/ -la

    - name: Clone do projeto de infraestrutura
      git:
        repo: git@github.com:mycloudlab/demo-ansible.git
        dest: infra
        version: main
    
    - name: seta a versão nova em desenvolvimento
      copy:
        content: "dev_version: {{ version.stdout }}"
        dest: infra/configs/dev/config.yml

    - name: commit new version
      shell: cd infra && git add . && git commit -a -m "update dev version" && git push