---
- name: cria o gateway de internet para aplicação pet-clinic
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{vpcdata.vpc.id}}"
    state: present
    tags:
      Name: igw-pet-clinic-{{env}}
      env: {{env}}
  register: igwdata