---
- name: ec2 security group
  amazon.aws.ec2_group:
    name: sec_group_petclinic_{{env}}
    description: an example EC2 group
    vpc_id: "{{vpcdata.vpc.id}}"
    region: us-east-2
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
