---
- name: ec2 security group
  amazon.aws.ec2_group:
    name: sec_group_petclinic_{{env}}
    description: sec group para app petclinic {{env}}
    vpc_id: "{{vpcdata.vpc.id}}"
    region: "{{AWS_REGION}}"
    rules:
      - proto: tcp
        from_port: 5000
        to_port: 5000
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
