---
- name: instala postgres
  yum:
    name:
      - postgresql-server
      - python3-psycopg2
    state: present
  notify: restart postgresql

- name: verifica se o banco foi iniciado
  stat:
    path: /var/lib/pgsql/data/pg_hba.conf
  register: db_init

- name: inicializa o banco
  shell: /usr/bin/postgresql-setup --initdb
  when: not db_init.stat.exists


- name: configura hba.conf
  lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    line: 'host all all 0.0.0.0/0 trust'
    insertbefore: EOF
  notify: restart postgresql

- name: configura listener postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    line: "listen_addresses='*'"
    insertbefore: EOF
  notify: restart postgresql

- name: configura porta postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    line: "port = 5432"
    insertbefore: EOF
  notify: restart postgresql
  
- name: systemctl postgresql enabled
  service:
    name: postgresql
    state: started
    enabled: yes
  notify: restart postgresql

