---
- name: instala postgres
  yum:
    name:
      - postgresql-server
    state: present
  notify: restart postgresql

- name: inicializa o banco
  shell: /usr/bin/postgresql-setup --initdb
  ignore_errors: True

- name: systemctl postgresql enabled
  service:
    name: postgresql
    state: started
    enabled: yes
  notify: restart postgresql

