---
- name: instala postgres
  yum:
    name:
      - postgresql-server
    state: present
  notify: restart postgresql

- name: systemctl postgresql enabled
  service:
    name: postgresql
    state: started
    enabled: yes
  notify: restart postgresql
